version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: watch-party-postgres
    environment:
      POSTGRES_DB: watch_party
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - watch_party_network

  redis:
    image: redis:7-alpine
    container_name: watch-party-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - watch_party_network

  minio:
    image: minio/minio:latest
    container_name: watch-party-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - watch_party_network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  watch_party_network:
    name: "watch_party_network"